apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: xiu-prod-autoscaling
  namespace: xiu-prod-ns
  labels:
    app: xiu
    environment: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: xiu-prod-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60